name: Update README with Latest Release

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: latest_release
        uses: actions/github-script@v5
        with:
          script: |
            const latestRelease = await github.repos.getLatestRelease({ owner: context.repo.owner, repo: context.repo.repo });
            console.log(latestRelease.data.tag_name);
            console.log(latestRelease.data.assets[0].browser_download_url); // Assuming the first asset is the one you want
            core.setOutput("tag_name", latestRelease.data.tag_name);
            core.setOutput("download_url", latestRelease.data.assets[0].browser_download_url);

      - name: Update README
        run: |
          sed -i "s|<a href=\"https://github.com/Wallemations/ss13_artmapper/releases/download/.*\">|<a href=\"${{ steps.latest_release.outputs.download_url }}\">|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with latest release download link"
          git push
